import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Checkbox from "~/components/Checkbox/Checkbox";

import Layout from "~/components/Layout/Layout";

import { api, type RouterOutputs } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.challenges.getTasksFromLastChallenge.useQuery();

  type TasksFromUserChallenge =
    RouterOutputs["challenges"]["getTasksFromLastChallenge"];

  return (
    <>
      <Head>
        <title>League homepage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1 className="mb-20 text-8xl font-extrabold tracking-tight">League</h1>
        <h2 className="mb-4 text-xl">Current challenge</h2>
        <div className="mb-20 flex flex-col items-center gap-2  border-2 border-black px-8 py-4">
          {data?.challenge &&
            data.challenge.tasks.map((task, i) => (
              <div key={i} className="flex flex-row gap-8">
                <p>{task.title}</p>
                <input type="checkbox" value={i} />
              </div>
            ))}
          <p className="font-bold">+{data?.challenge.point || 0}p</p>
        </div>
        <h2 className="mb-4 text-xl">Who completed this challenge already?</h2>
        <div className="mb-20 flex flex-col gap-4  border-2 border-black px-8 py-4">
          <div className="flex flex-row justify-between gap-6">
            <p className="font-bold">1st</p>
            <p>Marexo - 10.4.2023 18:45</p>
            <p className="font-bold">+3p</p>
          </div>
          <div className="flex flex-row justify-between gap-6">
            <p className="font-bold">2nd</p>
            <p>Richie - 10.4.2023 18:45</p>
            <p className="font-bold">+2p</p>
          </div>
          <div className="flex flex-row justify-between gap-6 text-gray-400">
            <p className="font-bold">3rd</p>
            <p>No one yet</p>
            <p className="font-bold">+1p</p>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default Home;
