import { type NextPage } from "next";
import Head from "next/head";
import Checkbox from "~/components/Checkbox/Checkbox";

import Layout from "~/components/Layout/Layout";

// import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const { data } = api.challenges.getAllChallenges.useQuery();
  // const { data: users } = api.challenges.getAllUsers.useQuery();

  return (
    <>
      <Head>
        <title>League homepage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1 className="mb-20 text-8xl font-extrabold tracking-tight">
          Street League
        </h1>
        <h2 className="mb-4 text-xl">Current challenge</h2>
        <div className="mb-20 flex flex-col items-center gap-2  border-2 border-black px-8 py-4">
          <div className="flex flex-row gap-8">
            <p>run 20km in total</p>
            <Checkbox />
          </div>
          <div className="flex flex-row gap-8">
            <p>3h boxing training</p>
            <Checkbox />
          </div>
          <div className="flex flex-row gap-8">
            <p>do 100 pushups</p>
            <Checkbox />
          </div>
          <p className="font-bold">+8p</p>
        </div>
        <h2 className="mb-4 text-xl">Who completed this challenge already?</h2>
        <div className="mb-20 flex flex-col gap-4  border-2 border-black px-8 py-4">
          <div className="flex flex-row justify-between gap-6">
            <p className="font-bold">1st</p>
            <p>Marexo - 10.4.2023 18:45</p>
            <p className="font-bold">+3p</p>
          </div>
          <div className="flex flex-row justify-between gap-6">
            <p className="font-bold">2nd</p>
            <p>Richie - 10.4.2023 18:45</p>
            <p className="font-bold">+2p</p>
          </div>
          <div className="flex flex-row justify-between gap-6 text-gray-400">
            <p className="font-bold">3rd</p>
            <p>No one yet</p>
            <p className="font-bold">+1p</p>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default Home;
